version: '3.9'

services:
  postgres:
    image: postgres
    container_name: cart-service-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql
    ports:
      - 5436:5432

volumes:
  postgres:
